#pragma once

/*CUSTOM CONFIG*/
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_TYPING_HEATMAP_SLIM
#define LEADER_TIMEOUT 600
